# Basic dbt_project.yml configuration

name: 'app_dbt' # This is usually the project name
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'app_dbt' # Make sure this matches the profile name in profiles.yml

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"] # Ensure dbt knows where seeds are
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  app_dbt:
    staging:
      +materialized: table
    analytics:
      +materialized: table
    example:
      +materialized: view